
import Navbar from '@/components/Navbar'
import {AuthProvider} from '@/context/AuthContext';
import './globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
        <Navbar/>
        {children}
        </AuthProvider>
        </body>
    </html>
  )
}
